# Generated by Django 3.2 on 2023-05-16 15:32

from django.db import migrations, models

import users.validator


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор'), ('moderator', 'Модератор')], default='user', max_length=9, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите логин, не более 150 символов', max_length=150, unique=True, validators=[users.validator.username_valid], verbose_name='Логин'),
        ),
    ]
