# Generated by Django 3.2 on 2023-05-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230516_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='XXXX', help_text='Введите код подтверждения,который был отправлен на ваш email', max_length=150, verbose_name='Код'),
        ),
    ]
