# Generated by Django 3.2 on 2023-05-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230516_1532'),
        ('users', '0003_alter_user_confirmation_code'),
    ]

    operations = [
    ]
