# Generated by Django 3.2 on 2023-05-11 07:54

from django.db import migrations, models
import users.validator


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230509_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь'},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('user', 'User')], default='user', max_length=16, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email_адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validator.username_valid], verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username',)},
        ),
    ]
