# Generated by Django 3.2 on 2023-05-11 17:30

from django.db import migrations, models
import users.validator


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230511_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Введите адрес электронной почты для регистрации.', max_length=254, unique=True, verbose_name='email_адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите логин, не более 150 символов', max_length=150, unique=True, validators=[users.validator.username_valid], verbose_name='Логин'),
        ),
    ]
