# Generated by Django 3.2 on 2023-05-15 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now, verbose_name='Описание произведения'),
            preserve_default=False,
        ),
    ]
